// Write CHANGELOG.md from the git history.
//
// `task-1804` §6: *"201 commits and 34 minor versions with no record of what changed between them
// that a user could read. The commit history is greppable by ticket, which serves a developer and
// not a person deciding whether to update."*
//
// So the history is turned into that record, and it can be because of a convention the repository
// already keeps: **every commit that does something starts with its ticket**, `task-1804: …`. That
// prefix is what separates the work from the bookkeeping — the version bumps `tools/release.ps1`
// makes are `Unluminous <version>` and are not tickets, which is exactly what makes them the
// boundaries between one release and the next.
//
// ## Why a script rather than a file people edit
//
// A hand-written changelog is a file somebody forgets. This one is regenerated by `release.ps1` and
// `release.sh` on every release, from tags that are already there, so it cannot fall behind — the
// same argument `unluminous-cli/src/documentation.rs` makes about `commands.md` being a test.
//
// ## Node rather than PowerShell or bash
//
// Because there are two release scripts and one of them runs on a Mac with no `pwsh`. Node is what
// both platforms have here, and one reading of the history is better than two that have to agree.
//
// Usage:
//   node tools/changelog.mjs                   writes CHANGELOG.md
//   node tools/changelog.mjs --release 0.51.0  the same, with HEAD written up as that version
//   node tools/changelog.mjs --check           exits 1 if the file's released sections are stale
//   node tools/changelog.mjs --stdout          prints it instead of writing it
//
// ## Why `--release` exists
//
// **`task-1984` WP5.** A release script writes the changelog **before** it tags, so that the file is
// in the release's own commit -- and at that moment the version being released has no tag, so
// `releases()` cannot see it and everything it holds is written under `## Unreleased`. The tag is
// then made and the file is stale from that instant: 0.50.0 was cut and its section never existed,
// and `--check` reported it one release later, because what it compares is the released history and
// 0.50.0 only became released history after the tag.
//
// So a release says which version it is cutting, and HEAD is written up under that heading with
// today's date. What `--check` compares afterwards is the same text, because the tag it then reads
// points at the commit this was run against.

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const repo = join(dirname(fileURLToPath(import.meta.url)), '..')

/** Run git in the repository and answer what it printed. */
function git(...args) {
  return execFileSync('git', ['-C', repo, ...args], { encoding: 'utf8' }).trimEnd()
}

/**
 * Every `vN.N.N` tag, newest first, with the date it was made.
 *
 * By the tag's own date rather than by its name, because a version is released when it is released
 * and sorting names would put `v0.9.0` after `v0.34.2`.
 */
function releases() {
  const lines = git('for-each-ref', '--sort=-creatordate', '--format=%(refname:short)\t%(creatordate:short)', 'refs/tags/v*')
  if (!lines) return []
  return lines.split('\n').map(line => {
    const [tag, date] = line.split('\t')
    return { tag, date, version: tag.replace(/^v/, '') }
  })
}

/**
 * The ticket-prefixed subjects between two points in the history, oldest first.
 *
 * `from` is exclusive and may be undefined, which means the beginning of the history. Anything that
 * is not a ticket is dropped: a version bump, a merge, a typo fix nobody filed. That is the whole of
 * the filtering, and it is deliberate — a line a person can read is a line somebody wrote a ticket
 * for.
 */
function work(from, to) {
  const range = from ? `${from}..${to}` : to
  const lines = git('log', '--no-merges', '--reverse', '--pretty=%s', range)
  if (!lines) return []
  return lines
    .split('\n')
    .map(subject => subject.trim())
    .filter(subject => /^task-\d+:/.test(subject))
    .map(subject => {
      const [, ticket, said] = subject.match(/^(task-\d+):\s*(.*)$/)
      return { ticket, said: said.charAt(0).toUpperCase() + said.slice(1) }
    })
}

/** The version being released, when a release script said so, or nothing. */
function releasing() {
  const at = process.argv.indexOf('--release')
  if (at === -1) return null
  const version = process.argv[at + 1]
  if (!version || !/^\d+\.\d+\.\d+$/.test(version)) {
    console.error('--release wants a version, as in: node tools/changelog.mjs --release 0.51.0')
    process.exit(2)
  }
  return version
}

/** The whole document. */
function changelog() {
  const out = [
    '# Changelog',
    '',
    'What changed in each release of Unluminous, for somebody deciding whether to update.',
    '',
    'Written by `tools/changelog.mjs` from the git history, and rewritten by `tools/release.ps1` and',
    '`tools/release.sh` on every release, so it cannot fall behind. One line per ticket; the version',
    'bumps the release script makes are left out, because they are the boundaries rather than the work.',
    '',
  ]
  const tags = releases()
  const cutting = releasing()
  const unreleased = work(tags[0]?.tag, 'HEAD')
  if (cutting) {
    // HEAD is about to become `v<cutting>`, so what is between the last tag and here is that
    // version's section rather than `Unreleased`. Dated today, which is the date the tag will carry.
    out.push(`## ${cutting} — ${new Date().toISOString().slice(0, 10)}`, '')
    if (unreleased.length === 0) {
      out.push('- No ticketed work; a rebuild of the version before it.', '')
    } else {
      for (const entry of unreleased) out.push(`- ${entry.said} (\`${entry.ticket}\`)`)
      out.push('')
    }
  } else if (unreleased.length > 0) {
    out.push('## Unreleased', '')
    for (const entry of unreleased) out.push(`- ${entry.said} (\`${entry.ticket}\`)`)
    out.push('')
  }
  for (let index = 0; index < tags.length; index += 1) {
    const { tag, date, version } = tags[index]
    const entries = work(tags[index + 1]?.tag, tag)
    out.push(`## ${version} — ${date}`, '')
    if (entries.length === 0) {
      // Said rather than left blank: a release with nothing under it is a real thing -- a rebuild,
      // or a version bumped twice -- and an empty heading reads as a mistake.
      out.push('- No ticketed work; a rebuild of the version before it.', '')
      continue
    }
    for (const entry of entries) out.push(`- ${entry.said} (\`${entry.ticket}\`)`)
    out.push('')
  }
  return out.join('\n')
}

/**
 * A changelog with its `## Unreleased` section taken out, which is what `--check` compares.
 *
 * `task-1922`: the check compared the whole file, and the file holds a section built from every
 * commit made since the last tag -- so it was wrong the moment anybody committed anything, and the
 * `checks` job went red on every ordinary push. A gate that is red whenever work is in progress is a
 * gate nobody reads, which is the fault this ticket exists to fix, one file along.
 *
 * What the check is really about is the **released** history: a version whose entries have gone
 * stale, or a release with no section at all. Both release scripts rewrite the whole file, Unreleased
 * and all, so nothing is lost by leaving that one section out of the comparison.
 */
function released(text) {
  const lines = text.split('\n')
  const heading = lines.findIndex((line) => line.startsWith('## Unreleased'))
  if (heading === -1) {
    return text.trimEnd()
  }
  const next = lines.findIndex((line, at) => at > heading && line.startsWith('## '))
  return next === -1 ? '' : lines.slice(next).join('\n').trimEnd()
}

const wanted = changelog()
const path = join(repo, 'CHANGELOG.md')
if (process.argv.includes('--stdout')) {
  process.stdout.write(wanted)
} else if (process.argv.includes('--check')) {
  let have = ''
  try {
    have = readFileSync(path, 'utf8').replace(/\r\n/g, '\n')
  } catch {
    have = ''
  }
  if (released(have) !== released(wanted)) {
    console.error('CHANGELOG.md is not what the history says. Run: node tools/changelog.mjs')
    process.exit(1)
  }
  console.log("CHANGELOG.md's released sections are up to date.")
} else {
  writeFileSync(path, wanted, 'utf8')
  const releaseCount = releases().length
  console.log(`Wrote CHANGELOG.md: ${releaseCount} releases.`)
}
